Add config to override JDK default compiler
folio-org/mod-meta-storage pull request #24
Opened 2022-05-13 21:10 UTC by skoczko

This only works for running tests and when running via `mvn exec:exec`
This DOES NOT fix the issue when running from the container -- for that
we will need to alter the Java startup script in the base image.

2022-05-13 21:11 UTC, skoczko commented
@adamdickmeiss Yikes, I see that you already have a branch for this. I'lll close it then and add the exec config on top of your branch.

2022-05-17 10:03 UTC, adamdickmeiss requested changes

2022-05-17 10:03 UTC, adamdickmeiss commented on etc/launch-from-modules.sh
> +cd ../server/target/
Can you put it in server instead? I don't like so many directories in root.

2022-05-17 10:03 UTC, adamdickmeiss commented on server/pom.xml
> +              <artifactSet>
I'd prefer we do not exclude these . Because it will make the fat jar without options fail upon start.

2022-05-17 10:47 UTC, adamdickmeiss approved these changes
descriptors/DeploymentDescriptor-template.json should be updated too. It will break as exclusions are removed. The change can be done  in separate PR.

2022-05-17 14:25 UTC, merged